Repository DavidePastore/Slim-Validation, pull requests merged in 2022-12, with the labels that each got.

#65 Remove composer lock file
  .gitignore
  composer.json
  composer.lock
Labels: dependencies

#67 Remove --no-suggest option from composer install
  .github/workflows/continuous-integration.yml
Labels: enhancement

#68 Move changes from 3.0 to 4.0
  .github/workflows/continuous-integration.yml
  .gitignore
  .travis.yml
  README.md
  composer.json
  composer.lock
Labels: 4.*

#61 Slim4 Support w/ Test updates
  .github/workflows/continuous-integration.yml
  README.md
  composer.json
  phpunit.xml.dist
  src/Validation.php
  tests/ValidationTest.php
Labels: enhancement, 4.*

#72 Change the status badge branch from master to 4.0
  README.md
Labels: enhancement, 4.*
